<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <title>Akimario</title>
</head>

<body>
    
    <header>
        <nav>
            <div>
                <a href="index.php">Accueil</a>
            </div>
            <?php if(!isset($_SESSION['user'])): ?>
                
                <div>
                    <a href="signup.php">S'inscrire</a>
                    <a href="login.php">Se connecter</a>
                </div>
            <?php endif; ?>
            
            <?php if(isset($_SESSION['user'])): ?>
                <div>
                    <a href="account.php">Mon compte</a>
                    <a href="logout.php">Se déconnecter</a>
                </div>
            <?php endif; ?>
        </nav>
    </header>
    
    <main>
        
        <img src="img/genie_miitopia.png">
        
        <div class="container">
        
            <?php include "$template.phtml" ?>
        
        </div>
    
    </main>
</body>

<footer>
    <p>© 2025, Akimario, site créé par Ryenn.</p>
    <p>Akimario n'est pas un site officiel, mais un site de fan ayant pour but d'informer et de rassembler une communauté autour de la passion pour les jeux Super Mario.</p>
    <p class="last-line">Tous les personnages ainsi que les jeux et leurs illustrations appartiennent à Nintendo.</p>
</footer>

</html>