<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <title>Akimario</title>
</head>

<body>
    
    <header>
        
    </header>
    
    <main>
        
        <?php include "$template.phtml" ?>
        
    </main>
</body>

<footer>
    <p>© 2025, Akimario, site créé par Ryenn.</p>
    <p>Akimario n'est pas un site officiel, mais un site de fan ayant pour but d'informer et de rassembler une communauté autour de la passion pour les jeux Super Mario.</p>
    <p>Tous les personnages ainsi que les jeux et leurs illustrations appartiennent à Nintendo.</p>
</footer>

</html>