<div class="signup">
    
    <h1>Inscription</h1>
    
    <div class="container">
        
        <form method="POST">
            
            <label for="pseudo">Pseudo :</label>
            <input type="text" id="pseudo" name="pseudo" required>
            
            <label for="email">Email :</label>
            <input type="text" id="email" name="email" required>
    
            <label for="new-password">Mot de passe :</label>
            <input type="password" id="new-password" name="password" required>
            
            <p>Vous avez un compte ?<a href="index.php"> Connectez-vous !</a></p>
            
            <button>S'inscrire</button>
        </form>

        
    </div>
</div>
    