<div class="signup">
    
    <h1>Inscription</h1>
    
    <div class="form">
        
        <form method="POST">
            
            <div>
                <label for="pseudo">Pseudo :</label>
                <input type="text" id="pseudo" name="pseudo" value="<?= isset($_POST["pseudo"]) ? $_POST["pseudo"]: "" ?>" required>
            </div>
            
            <div>
                <label for="email">Email :</label>
                <input type="text" id="email" name="email" value="<?= isset($_POST["email"]) ? $_POST["email"]: "" ?>" required>
            </div>
            
            <div>
                <label for="new-password">Mot de passe :</label>
                <input type="password" id="new-password" name="password" required>
            </div>
            
            <p>Vous avez un compte ? <a href="login.php">Connectez-vous !</a></p>
            
            <button>S'inscrire</button>
        </form>

        <?php if (!empty($errorMessage)): ?>
            <div class="error">
                <?= htmlspecialchars($errorMessage) ?>
            </div>
        <?php endif; ?>

        
    </div>
</div>
    